# Generated by Django 5.0.7 on 2025-10-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_commandcrm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandCrm',
            new_name='CommentCrm',
        ),
    ]
